apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        clusterName: "health-hackathon"
        region: "eu-west-2"
        vpcId: "vpc-0d2f30d2aac2746ef"
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::417732881703:role/health-hackathon-aws-lb-controller"
