apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instana-agent
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        cluster:
          name: umbrella-health
        zone:
          name: umbrella-health

