apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instana-agent
  namespace: argocd
spec:
  destination:
    namespace: instana-agent
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://agents.instana.io/helm"
    chart: "instana-agent"
    targetRevision: "2.0.53"
    helm:
      valuesObject:
        agent:
          keysSecret: instana-agent        # var olan Secret; anahtarlar: key, downloadKey
          endpointHost: ingress-green-saas.instana.io
          endpointPort: "443"
        cluster:
          name: ""
        zone:
          name: ""
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

